### PR TITLE
Add PHP 8 to the list of supported PHP versions

### PR DESCRIPTION
**Pull request by nikeee**
I want to use this library in a PHP 8 project and composer complains that it requires PHP 7.2.

I don't think that this library won't run on PHP 8, though I did not test it.

### CODE REVIEW

**Comment by nikeee** [comment]
I've also added two methods that process binary strings in a different branch:
https://github.com/carlosafonso/php-base24/compare/master...nikeee:php-base24:master

That way, one can use [`random_bytes`](https://www.php.net/random_bytes) and feed the output diretly to the encoder.

Are you interested in those, too? I really need them and would like to contribute to you (upstream) rather than maintaining my own fork.

**Comment by nikeee** [comment]
@carlosafonso any thoughts on this?

**Comment by carlosafonso** [comment]
Hey @nikeee , I completely missed this one. My deepest apologies. Thank you for your contribution!

**Comment by carlosafonso** [comment]
Feel free to open another PR with https://github.com/carlosafonso/php-base24/compare/master...nikeee:php-base24:master and we can discuss further.

**Pull request merged**
